volumes:
  db-data:
    driver: local

version: '3'
services:
  app:
    build: .
    command: ["yarn","dev"]
    #command: /bin/bash -c "while true; do sleep 10; done"
    volumes:
      - .:/usr/src/app
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:9229:9229"
    depends_on:
      - db
      - mongo
      - mail
      - redis
  
  db:
    image: postgres:11
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  mongo:
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"

  mail:
    image: mailhog/mailhog
    ports:
      - "127.0.0.1:8025:8025"
      - "127.0.0.1:1025:1025"

  redis:
    image: redis
    ports:
      - "127.0.0.1:16379:6379"
